# Generated by Django 4.2.21 on 2025-05-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=70, verbose_name="Nome Completo")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("endereco", models.CharField(max_length=100, verbose_name="Endereço")),
                ("data", models.DateField(verbose_name="Data de Coleta")),
                ("hora", models.TimeField(verbose_name="Hora da Coleta")),
                (
                    "observacao",
                    models.CharField(max_length=999, verbose_name="Observação"),
                ),
            ],
        ),
    ]
