# Generated by Django 4.2.21 on 2025-05-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reciclagem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PontoColeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Ponto de Coleta"),
                ),
                ("endereco", models.CharField(max_length=300, verbose_name="Endereço")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefone"
                    ),
                ),
            ],
        ),
    ]
